CREATE TABLE IF NOT EXISTS players (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,  
  password_hash VARCHAR(255) NOT NULL,
  level INT NOT NULL DEFAULT 1, 
  experience BIGINT NOT NULL DEFAULT 0, 
  rank VARCHAR(50) NOT NULL,   
created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);